namespace Secrets;

public record Secrets(
    string OpenAiApiKey,
    string AzureOpenAiEndpoint,
    string AzureOpenAiKey,
    string ChatDeploymentName,
    string EmbeddingModelName,
    string MicrosoftFoundryEndpoint,
    string AzureAiFoundryAgentId,
    string BingApiKey,
    string HuggingFaceApiKey,
    string OpenRouterApiKey,
    string CohereApiKey,
    string CerebrasApiKey,
    string GroqApiKey,
    string ApplicationInsightsConnectionString,
    string GoogleGeminiApiKey,
    string XAiGrokApiKey,
    string TrelloApiKey,
    string TrelloToken,
    string AnthropicApiKey,
    string MistralApiKey,
    string OpenWeatherApiKey,
    string AmazonBedrockApiKey,
    string EmailUsername,
    string EmailPassword);
